version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: saturday
    ignore:
      - dependency-name: *
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    commit-message:
      prefix: deps
    labels:
      - bot
