ifndef::manversion[:manversion: 0.0.0]

= git-draft(1)
Matthieu Monsch
v{manversion}
:doctype: manpage
:manmanual: GIT-DRAFT
:mansource: GIT-DRAFT


== Name

git-draft - git-friendly code assistant

IMPORTANT: `git-draft` is WIP.


== Synopsis

[verse]
'git draft' [options] [--generate] [--bot BOT] [--edit] [--no-reset | --reset]
                      [--sync] [TEMPLATE [VARIABLE...]]
'git draft' [options] --finalize [--clean | --revert] [--delete]
'git draft' [options] --show-drafts [--json]
'git draft' [options] --show-prompts [--json] [PROMPT]
'git draft' [options] --show-templates [--json | [--edit] TEMPLATE]


== Description

`git-draft` is a git-centric way to edit code using AI.


== Options

-b BOT::
--bot=BOT::
  Bot name.

-c::
--clean::
  TODO

-d::
--delete::
  Delete finalized branch.

-e::
--edit::
  Edit.

-F::
--finalize::
  TODO

-G::
--generate::
  TODO

-h::
--help::
  Show help message and exit.

-j::
--json::
  Use JSON output.

--log::
  Show log path and exit.

--reset::
--no-reset::
  TODO

-r::
--revert::
  Abandon any changes since draft creation.

--root::
  Repository search root.

-D::
--show-drafts::
  TODO

-P::
--show-prompts::
  TODO

-T::
--show-templates::
  TODO

-s::
--sync::
  Create a sync commit with any changes.

-t TIMEOUT::
--timeout=TIMEOUT::
  Action timeout.

--version::
  Show version and exit.


== Examples

The workhorse command is `git draft --generate` which leverages AI to edit our code.
A prompt can be specified as standard input, for example `echo "Add a test for compute_offset in chart.py" | git draft --generate`.
If no prompt is specified and stdin is a TTY, `$EDITOR` will be opened to enter the prompt.

If not on a draft branch, a new draft branch called `drafts/$parent/$hash` will be created (`$hash` is a random suffix used to guarantee uniqueness of branch names) and checked out.
By default any unstaged changes are then automatically added and committed (`draft! sync`).
This behavior can be disabled by passing in `--stash`, which will instead add them to the stash.
Staged changes are always committed.

The prompt automatically gets augmented with information about the files in the repository, and give the AI access to tools for reading and writing files.
Once the response has been received and changes applied, a commit is created (`draft! prompt: a short summary of the change`).

The `--generate` step can be repeated as many times as needed.
Once you are satisfied with the changes, run `git draft --finalize` to apply them.
This will check out the branch used when creating the draft, adding the final state of the draft to the worktree.
Note that you can come back to an existing draft anytime (by checking its branch out), but you will not be able to apply it if its origin branch has moved since the draft was created.


== See also

`git(1)`
