ifndef::manversion[:manversion: 0.0.0]

= git-draft(1)
Matthieu Monsch
v{manversion}
:doctype: manpage
:manmanual: GIT-DRAFT
:mansource: GIT-DRAFT


== Name

git-draft - git-friendly code assistant


== Synopsis

*git-draft* _-C_ _NAME_

*git-draft* _-P_

*git-draft* _-A_

*git-draft* _-D_ _[-b BRANCH]_


== Description

_git-draft_ is a git-centric way to edit code using AI.

=== How it works

When you create a new draft with `git draft -C $name`, a new branch called `$branch/drafts/$name-$hash` is created (`$hash` is a random suffix used to guarantee uniqueness of branch names) and checked out.
Additionally, any uncommitted changes are automatically committed (`draft! sync`).

Once the draft is created, we can use AI to edit our code using `git draft -E`.
It expects the prompt as standard input, for example `echo "Add a test for compute_offset in chart.py" | git draft -P`.
The prompt will automatically get augmented with information about the files in the repository, and give the AI access to tools for reading and writing files.
Once the response has been received and changes, applied a commit is created (`draft! prompt: a short summary of the change`).

The prompt step can be repeated as many times as needed. Once you are satisfied with the changes, run `git draft -A` to apply them.
This will check out the branch used when creating the draft, adding the final state of the draft to the worktree.
Note that you can come back to an existing draft anytime (by checking its branch out), but you will not be able to apply it if its origin branch has moved since the draft was created.

Finally, calling `git draft -D` will delete all drafts associated with a branch.
By default the currently active branch is used, you can use the `-b` option to select another.
You can also delete the drafts manually by deleting their branches using `git branch`.


== See also

_git(1)_
