ifndef::manversion[:manversion: 0.0.0]

= git-draft(1)
Matthieu Monsch
v{manversion}
:doctype: manpage
:manmanual: GIT-DRAFT
:mansource: GIT-DRAFT


== Name

git-draft - git-friendly code assistant

IMPORTANT: _git-draft_ is WIP.
Options documented below may not be implemented yet.


== Synopsis

*git-draft* _[--generate]_ _[--prompt PROMPT]_ _[--reset]_ _[TEMPLATE [...]]_

*git-draft* _--finalize_ _[--delete]_

*git-draft* _--discard_ _[--delete]_


== Description

_git-draft_ is a git-centric way to edit code using AI.

=== How it works


The workhorse command is `git draft --generate` which leverages AI to edit our code.
A prompt can be specified as standard input, for example `echo "Add a test for compute_offset in chart.py" | git draft --generate`.
If no prompt is specified and stdin is a TTY, `$EDITOR` will be opened to enter the prompt.

If not on a draft branch, a new draft branch called `drafts/$parent/$hash` will be created (`$hash` is a random suffix used to guarantee uniqueness of branch names) and checked out.
By default any unstaged changes are then automatically added and committed (`draft! sync`).
This behavior can be disabled by passing in `--stash`, which will instead add them to the stash.
Staged changes are always committed.

The prompt automatically gets augmented with information about the files in the repository, and give the AI access to tools for reading and writing files.
Once the response has been received and changes applied, a commit is created (`draft! prompt: a short summary of the change`).

The `--generate` step can be repeated as many times as needed.
Once you are satisfied with the changes, run `git draft --finalize` to apply them.
This will check out the branch used when creating the draft, adding the final state of the draft to the worktree.
Note that you can come back to an existing draft anytime (by checking its branch out), but you will not be able to apply it if its origin branch has moved since the draft was created.


== See also

_git(1)_
