ifndef::manversion[:manversion: 0.0.0]

= git-draft(1)
Matthieu Monsch
v{manversion}
:doctype: manpage
:manmanual: GIT-DRAFT
:mansource: GIT-DRAFT


== Name

git-draft - git-friendly code assistant

IMPORTANT: `git-draft` is WIP.


== Synopsis

[verse]
git draft [options] [--new] [--accept... | --no-accept] [--bot BOT]
                    [--edit] [TEMPLATE [VARIABLE...]]
git draft [options] --quit
git draft [options] --templates [--json | [--edit] TEMPLATE]


== Description

`git-draft` is a git-centric way to edit code with AI.


== Options

-a::
--accept::
--no-accept::

Merge generated changes automatically, updating the working directory.
This option can be repeated up to 3 times, with the following behavior at each level:

* `-a`: Merge changes conservatively, flagging any conflicts for manual user resolution.
* `-aa`: Merge changes aggressively, resolving all conflicts in favor of the generated change.
* `-aaa`: Merge changes aggressively (same as `-aa`) then run `--quit` automatically.

By default, changes are not merged - keeping the working directory untouched.
A different default can be set in the configuration file.
When doing so, the `--no-accept` flag can be used to disable merging at CLI invocation time.

-b BOT::
--bot=BOT::

Bot name.
Defaults to the first bot defined in the configuration.

-e::
--edit::

Enable interactive editing of draft prompts and templates.
See `--new` and `--templates` for details.

-h::
--help::
  Show help message and exit.

-j::
--json::
  Use JSON output.

--log-path::
  Show log path and exit.

-N::
--new::
  Create an AI-generated draft.
  If the `--edit` option is set, an interactive editor will be opened with the rendered prompt to allow modification before it is forwarded to the bot.

-Q::
--quit::
  Go back to the draft's origin branch, keeping the working directory's current state.
  This will delete the draft branch and its upstream.
  Generated commits remain available via `ref/drafts`.

--root::
  Repository search root.
  Defaults to the current working directory.

-T::
--templates::
  With no argument, lists available templates.
  With an template name argument, displays the corresponding template's contents or, if the `--edit` option is set, opens an interactive editor.

--version::
  Show version and exit.


== Examples

The workhorse command is `git draft --new` which leverages AI to edit code.
A prompt can be specified as standard input, for example `echo "Add a test for compute_offset in chart.py" | git draft --generate`.
If no prompt is specified and stdin is a TTY, `$EDITOR` will be opened to enter the prompt.

By default, the prompt gets augmented with information about the files in the repository, and give the AI access to tools for reading and writing files.
Once the response has been received and changes applied, a commit is created in a separate branch.

The `--generate` step can be repeated as many times as needed.
Once you are satisfied with the changes, run `git draft --finalize` to apply them.
This will check out the branch used when creating the draft, adding the final state of the draft to the worktree.
Note that you can come back to an existing draft anytime (by checking its branch out), but you will not be able to apply it if its origin branch has moved since the draft was created.


o Foo (main)
o Sync (drafts/123/pub)

# After generate without accept
o Foo (main)
o Sync (drafts/123)
o draft! <prompt> (drafts/123+, refs/drafts/123/1)

# After generate with accept
o Foo (main)
o Sync
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
o | Sync
|/
o Merge (drafts/123/pub)


o Foo (main)
o draft! sync
|\
| o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/1)
o Something
o Also something (drafts/123)


o Foo (main)
o draft! sync
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
o Something
o Also something (drafts/123/pub)
o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/2)


o Foo (main)
o draft! sync (drafts/123/pub)
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
 \
  o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/2)

o Foo (main)
o draft! sync (drafts/123/pub)
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
|/
o draft! sync
 \
  o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/2)


== See also

`git(1)`
