ifndef::manversion[:manversion: 0.0.0]

= git-draft(1)
Matthieu Monsch
v{manversion}
:doctype: manpage
:manmanual: GIT-DRAFT
:mansource: GIT-DRAFT


== Name

git-draft - git-friendly code assistant

IMPORTANT: `git-draft` is WIP.


== Synopsis

[verse]
git draft [options] [--generate] [--accept... | --no-accept] [--bot BOT]
                    [--edit] [--reset | --no-reset] [TEMPLATE [VARIABLE...]]
git draft [options] --finalize
git draft [options] --show-templates [--json | [--edit] TEMPLATE]


== Description

`git-draft` is a git-centric way to develop using AI.


== Options

-a::
--accept::
--no-accept::
  Check out generated changes automatically.
  Can be repeated.

-b BOT::
--bot=BOT::
  Bot name.

-e::
--edit::
  Enable interactive editing of prompts and templates.
  See `--generate` and `--show-templates` for details.

-F::
--finalize::
  Go back to the draft's origin branch with the current working directory.

-G::
--generate::
  Add an AI-generated commit.
  If the `--edit` option is set, an interactive editor will be open with the rendered prompt to allow modification before it is forwarded to the bot.

-h::
--help::
  Show help message and exit.

-j::
--json::
  Use JSON output.

--log::
  Show log path and exit.

--root::
  Repository search root.

-T::
--show-templates::
  Lists available templates.
  With an template name argument, displays the corresponding template's contents or, if the `--edit` option is set, opens an interactive editor.

-t TIMEOUT::
--timeout=TIMEOUT::
  Action timeout.

--version::
  Show version and exit.


== Examples

The workhorse command is `git draft --generate` which leverages AI to edit our code.
A prompt can be specified as standard input, for example `echo "Add a test for compute_offset in chart.py" | git draft --generate`.
If no prompt is specified and stdin is a TTY, `$EDITOR` will be opened to enter the prompt.

By default, the prompt gets augmented with information about the files in the repository, and give the AI access to tools for reading and writing files.
Once the response has been received and changes applied, a commit is created in a separate branch.

The `--generate` step can be repeated as many times as needed.
Once you are satisfied with the changes, run `git draft --finalize` to apply them.
This will check out the branch used when creating the draft, adding the final state of the draft to the worktree.
Note that you can come back to an existing draft anytime (by checking its branch out), but you will not be able to apply it if its origin branch has moved since the draft was created.


* Generate: create a new draft to the current folio, or create a new folio if none exists.
* Finalize
  ** Apply: include changes into origin branch.
  ** Discard: abandon folio.
  ** Save: return to original branch. Q: how to load after?
* List templates


o Foo (main)
o Sync (drafts/123/pub)

# After generate without accept
o Foo (main)
o Sync (drafts/123)
o draft! <prompt> (drafts/123+, refs/drafts/123/1)

# After generate with accept
o Foo (main)
o Sync
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
o | Sync
|/
o Merge (drafts/123/pub)


o Foo (main)
o draft! sync
|\
| o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/1)
o Something
o Also something (drafts/123)


o Foo (main)
o draft! sync
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
o Something
o Also something (drafts/123/pub)
o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/2)


o Foo (main)
o draft! sync (drafts/123/pub)
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
 \
  o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/2)

o Foo (main)
o draft! sync (drafts/123/pub)
|\
| o draft! prompt: <prompt> (refs/drafts/123/1)
|/
o draft! sync
 \
  o draft! prompt: <prompt> (drafts/123+, refs/drafts/123/2)


== See also

`git(1)`
