name: Tag
on:
  workflow_call:
    outputs:
      new-version:
        value: ${{ jobs.tag.outputs.new-version }}
      new-major-version:
        value: ${{ jobs.tag.outputs.new-major-version }}
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-version: ${{ steps.bump-version.outputs.new_version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Bump version and create tag
        id: bump-version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
