name: Test
on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 3
jobs:
  test:
    name: Test
    timeout-minutes: ${{ inputs.timeout-minutes }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up
        uses: mtth/draft/.github/actions/setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: poetry run pytest
